### ISSUE TITLE
This Composer package is currently not compatible with Composer 2.

### ISSUE THREAD

**Issue by AlwinGarside** [indigophp/doctrine-annotation-autoload#4]

**Comment by sagikazarmark** [comment]
This package is not maintained anymore. Feel free to fork it.

**Comment by AlwinGarside** [comment]
@sagikazarmark thanks for replying!

I actually already took the liberty and forked it:
https://github.com/Yogarine/doctrine-annotation-autoload

I added support voor Composer 2 and updated it with the latest changes in Composer.

If you want, you can provide it as replacement here and also mark your package as abandoned on packagist.org and suggest it as replacement there as well.

**Comment by sagikazarmark** [comment]
Done! Thanks a lot for picking it up.
